<?php
/**
 * Created by PhpStorm.
 * User: denys
 * Date: 6/27/18
 * Time: 14:57
 */
?>
<div class="owl-carousel owl-theme" data-mage-init='{"OwlCarousel":{} }'>
    <div class="item"><img src="<?php echo $this->getViewFileUrl('Elogic_CustomPage::images/logo1.png'); ?>" alt="Owl Image"></div>
    <div class="item"><img src="<?php echo $this->getViewFileUrl('Elogic_CustomPage::images/logo2.png'); ?>" alt="Owl Image"></div>
    <div class="item"><img src="<?php echo $this->getViewFileUrl('Elogic_CustomPage::images/logo3.png'); ?>" alt="Owl Image"></div>
    <div class="item"><img src="<?php echo $this->getViewFileUrl('Elogic_CustomPage::images/logo4.png'); ?>" alt="Owl Image"></div>
    <div class="item"><img src="<?php echo $this->getViewFileUrl('Elogic_CustomPage::images/logo5.png'); ?>" alt="Owl Image"></div>
    <div class="item"><img src="<?php echo $this->getViewFileUrl('Elogic_CustomPage::images/logo3.png'); ?>" alt="Owl Image"></div>
    <div class="item"><img src="<?php echo $this->getViewFileUrl('Elogic_CustomPage::images/logo1.png'); ?>" alt="Owl Image"></div>
    <div class="item"><img src="<?php echo $this->getViewFileUrl('Elogic_CustomPage::images/logo4.png'); ?>" alt="Owl Image"></div>
</div>
